project:
  type: book

book:
  title: "Probabilistic Scores of Classifiers: Calibration is not Enough"
  # author:
  # - name: Arthur Charpentier
  #   orcid: 0000-0003-3654-6286
  #   affiliations:
  #     - name: Université du Québec à Montréal
  # - name: Agathe Fernandes Machado
  #   orcid: 0009-0002-9743-9708
  #   affiliations:
  #     - name: Université du Québec à Montréal
  # - name: Emmanuel Flachaire
  #   orcid: 0000-0001-6241-5875
  #   affiliations:
  #     - name: Aix-Marseille School of Economics, Aix-Marseille Univ.
  # - name: Ewen Gallic
  #   orcid: 0000-0003-3740-2620
  #   affiliations:
  #     - name: Aix-Marseille School of Economics, Aix-Marseille Univ.
  # - name: François Hu
  #   orcid: 0009-0000-6093-6175
  #   affiliations:
  #     - name: Milliman France
  date: "08/15/2024"
  chapters:
    - index.qmd
    - part: "Subsampling"
      chapters:
        - book_target_distribution.qmd
    - part: "Metrics"
      chapters:
        - book_metrics.qmd
    - part: "Simulated Data"
      chapters:
        - book_ojeda.qmd
        - book_ojeda_trees.qmd
        - book_ojeda_forests.qmd
        - book_ojeda_forests_ntrees.qmd
        - book_ojeda_boosting.qmd
        - book_ojeda_glm.qmd
        - book_ojeda_gam.qmd
        - book_ojeda_gamsel.qmd
        - book_ojeda_comparison.qmd
    - part: "Real-world Data"
      chapters:
        - book_real_example.qmd
        - book_real_beta.qmd
        - book_real_estimations.qmd
        - book_real_results.qmd
    - references.qmd

bibliography: ./biblio.bib

fig-cap-location: top

format:
  html:
    from: markdown+emoji
    theme: cosmo
    highlight-style: github
    html-math-method: mathjax
    include-in-header:
    - file: mathjax-color.html

filters:
  - pseudocode

editor: source

